# Generated by Django 5.2 on 2025-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_remove_class_unique_active_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_config',
            field=models.JSONField(blank=True, help_text='A JSON object to serve as the configuration for the chosen contest format module. Leave empty to use None. Exact format depends on the contest format selected.', null=True, verbose_name='contest format configuration'),
        ),
        migrations.AlterField(
            model_name='contestparticipation',
            name='format_data',
            field=models.JSONField(blank=True, null=True, verbose_name='contest format specific data'),
        ),
    ]
