name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --dev
    - name: Lint with Ruff
      run: |
        uv run ruff --version
        uv run ruff check --config pyproject.toml .
    - name: Check formatting with Ruff
      run: uv run ruff format --check --config pyproject.toml .
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: |
        uv sync --extra test
        cp .ci.settings.py dmoj/local_settings.py
    - name: Start MySQL
      run: sudo systemctl start mysql.service
    - name: Run unit tests
      run: uv run coverage run --source=. manage.py test judge
    - name: Generate coverage report
      run: uv run coverage xml
    - uses: codecov/codecov-action@v4
  styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        run: npm install -g sass postcss-cli postcss autoprefixer
      - name: Build style.css
        run: ./make_style.sh
